<dt>
    <?= $this->formLabel($this->element->getName(), $this->element->getLabel()); ?>
</dt>
<dd class="icinga-module module-mapDatatype" data-icinga-module="mapDatatype">

    <input id="<?= $this->element->getName(); ?>"
           type="text"
           name="<?= $this->element->getName(); ?>"
           value="<?= htmlspecialchars($this->element->getValue(), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>"
        <?php if ($p = $this->element->getAttrib('placeholder')) {
            print 'placeholder="' . htmlspecialchars($p) . '"';
        } ?>/>
    <button type="button" id="director-map-btn-globe" class="control-button">
        <i class="icon-globe"></i>
    </button>
    <div id="col1" class="container icinga-module module-map" data-icinga-module="map">

        <div id="map-director" class="map map-home"></div>
        <p class="btn-container">
            <button type="button" id="director-map-btn-save" class="control-button">
                <i class="icon-ok"></i>
            </button>
            <button type="button" id="director-map-btn-cancel" class="control-button">
                <i class="icon-cancel"></i>
            </button>
        </p>
    </div>


    <?php if (count($this->element->getMessages()) > 0): ?>
        <?= $this->formErrors($this->element->getMessages()); ?>
    <?php endif; ?>
</dd>
