<dt>
    <?= $this->formLabel($this->element->getName(), $this->element->getLabel()); ?>
</dt>
<dd>

    <input id="<?= $this->element->getName(); ?>"
           type="text"
           name="<?= $this->element->getName(); ?>"
           value="<?= $this->element->getValue(); ?>"
        <? if ($p = $this->element->getAttrib('placeholder')) {
            print 'placeholder="' . htmlspecialchars($p) . '"';
        } ?>/>
    <button type="button" id="director-map-btn-globe" class="control-button" style="border-width: 1px;">
        <i class="icon-globe"></i>
    </button>
    <div id="col1" class="container icinga-module module-map" data-icinga-module="map"
         style="display: block; width: 100%;">

        <div id="map-director" class="map map-home" style="height: 250px; margin-top: 0px"></div>
        <p style="margin-top: 5px; text-align:right; max-width: unset;">
            <button type="button" id="director-map-btn-save" class="control-button" style="border-width: 1px;">
                <i class="icon-ok"></i>
            </button>
            <button type="button" id="director-map-btn-cancel" class="control-button" style="border-width: 1px;">
                <i class="icon-cancel"></i>
            </button>
        </p>
    </div>


    <?php if (count($this->element->getMessages()) > 0): ?>
        <?= $this->formErrors($this->element->getMessages()); ?>
    <?php endif; ?>
    <script type="text/javascript">
        var interval = setInterval(function () {
            if (typeof icinga == 'undefined') return;
            clearInterval(interval);

            var modulname = "mapDatatype";
            if (icinga.isLoadedModule(modulname)) {
                icinga.modules.mapDatatype.initialize();
            } else {
                icinga.loadModule(modulname)
            }

        }, 10);
    </script>
</dd>